name: flutter_template
description: A template to create Flutter applications.
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: ^0.17.0
  persistent_bottom_nav_bar: ^4.0.2
  http: ^0.13.3
  cached_network_image: ^3.1.0+1

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/placeholder.jpg
